# // Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# // SPDX-License-Identifier: MIT-0
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: tpcds-benchmark-10g-3iter-4inst-hostpath
  namespace: spark-operator
spec:
  type: Scala
  mode: cluster
  image: ghcr.io/aws-samples/eks-spark-benchmark:3.1.2
  imagePullPolicy: IfNotPresent
  sparkVersion: 3.1.2
  mainClass: com.amazonaws.eks.tpcds.BenchmarkSQL
  mainApplicationFile: local:///opt/spark/examples/jars/eks-spark-benchmark-assembly-1.0.jar
  hadoopConf:
    fs.default.name: "hdfs://aspyrou-1:9000"
  arguments:
  # TPC-DS data localtion
    - "hdfs:///tpcds-data"
  # results location
    - "hdfs:///tpcds-result"
  # Path to kit in the docker image
    - "/opt/tpcds-kit/tools"
  # Data Format
    - "parquet"
  # Scale factor (in GB)
    - "10"
  # Number of iterations
    - "3"
  # Optimize queries with hive tables
    - "false"
  # Filter queries, will run all if empty - "q98-v2.4,q99-v2.4,ss_max-v2.4,q95-v2.4"
    - "q64-v2.4,q70-v2.4,q82-v2.4" 
  # Logging set to WARN
    - "true"
  sparkConf:
    "spark.network.timeout": "2000s"
    "spark.executor.heartbeatInterval": "300s"
    # AQE
    "spark.sql.adaptive.enabled": "true"
    "spark.sql.adaptive.localShuffleReader.enabled": "true"
    "spark.sql.adaptive.coalescePartitions.enabled": "true"
    "spark.sql.adaptive.skewJoin.enabled": "true"
    # Remove
    spark.local.dir: /tmp/spark-local-dir
  driver:
    cores: 2
    coreLimit: "3.3"
    memory: "3g"
    serviceAccount: "spark-spark" 
    volumeMounts:
      - name: spark-local-dir-1
        mountPath: /tmp/spark-local-dir
  executor:
    cores: 2
    coreLimit: "3.3"
    memory: "3g"
    instances: 4
    volumeMounts:
      - name: spark-local-dir-1
        mountPath: /tmp/spark-local-dir
  volumes:    
    - name: "spark-local-dir-1"
      emptyDir: {}
  restartPolicy:
    type: Never